/* Autogenerated by mlir-tblgen; don't manually edit */

#ifdef GEN_PASS_DECL
// Generate declarations for all passes.
#define GEN_PASS_DECL_LIFERANGE
#undef GEN_PASS_DECL
#endif // GEN_PASS_DECL

//===----------------------------------------------------------------------===//
// LifeRange
//===----------------------------------------------------------------------===//
#ifdef GEN_PASS_DECL_LIFERANGE
#undef GEN_PASS_DECL_LIFERANGE
#endif // GEN_PASS_DECL_LIFERANGE
#ifdef GEN_PASS_DEF_LIFERANGE
namespace impl {

template <typename DerivedT>
class LifeRangeBase : public ::mlir::OperationPass<func::FuncOp> {
public:
  using Base = LifeRangeBase;

  LifeRangeBase() : ::mlir::OperationPass<func::FuncOp>(::mlir::TypeID::get<DerivedT>()) {}
  LifeRangeBase(const LifeRangeBase &other) : ::mlir::OperationPass<func::FuncOp>(other) {}
  LifeRangeBase& operator=(const LifeRangeBase &) = delete;
  LifeRangeBase(LifeRangeBase &&) = delete;
  LifeRangeBase& operator=(LifeRangeBase &&) = delete;
  ~LifeRangeBase() = default;

  /// Returns the command-line argument attached to this pass.
  static constexpr ::llvm::StringLiteral getArgumentName() {
    return ::llvm::StringLiteral("life-range");
  }
  ::llvm::StringRef getArgument() const override { return "life-range"; }

  ::llvm::StringRef getDescription() const override { return "Life Range Pass to show life cycles of variables"; }

  /// Returns the derived pass name.
  static constexpr ::llvm::StringLiteral getPassName() {
    return ::llvm::StringLiteral("LifeRange");
  }
  ::llvm::StringRef getName() const override { return "LifeRange"; }

  /// Support isa/dyn_cast functionality for the derived pass class.
  static bool classof(const ::mlir::Pass *pass) {
    return pass->getTypeID() == ::mlir::TypeID::get<DerivedT>();
  }

  /// A clone method to create a copy of this pass.
  std::unique_ptr<::mlir::Pass> clonePass() const override {
    return std::make_unique<DerivedT>(*static_cast<const DerivedT *>(this));
  }

  /// Return the dialect that must be loaded in the context before this pass.
  void getDependentDialects(::mlir::DialectRegistry &registry) const override {
    registry.insert<memref::MemRefDialect>();
  }

  /// Explicitly declare the TypeID for this class. We declare an explicit private
  /// instantiation because Pass classes should only be visible by the current
  /// library.
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(LifeRangeBase<DerivedT>)

protected:
private:
};
} // namespace impl
#undef GEN_PASS_DEF_LIFERANGE
#endif // GEN_PASS_DEF_LIFERANGE
#ifdef GEN_PASS_REGISTRATION

//===----------------------------------------------------------------------===//
// LifeRange Registration
//===----------------------------------------------------------------------===//

inline void registerLifeRange() {
  ::mlir::registerPass([]() -> std::unique_ptr<::mlir::Pass> {
    return mlir::liferange::createLifeRangePass();
  });
}

// Old registration code, kept for temporary backwards compatibility.
inline void registerLifeRangePass() {
  ::mlir::registerPass([]() -> std::unique_ptr<::mlir::Pass> {
    return mlir::liferange::createLifeRangePass();
  });
}

//===----------------------------------------------------------------------===//
//  Registration
//===----------------------------------------------------------------------===//

inline void registerPasses() {
  registerLifeRange();
}
#undef GEN_PASS_REGISTRATION
#endif // GEN_PASS_REGISTRATION
// Deprecated. Please use the new per-pass macros.
#ifdef GEN_PASS_CLASSES

template <typename DerivedT>
class LifeRangeBase : public ::mlir::OperationPass<func::FuncOp> {
public:
  using Base = LifeRangeBase;

  LifeRangeBase() : ::mlir::OperationPass<func::FuncOp>(::mlir::TypeID::get<DerivedT>()) {}
  LifeRangeBase(const LifeRangeBase &other) : ::mlir::OperationPass<func::FuncOp>(other) {}
  LifeRangeBase& operator=(const LifeRangeBase &) = delete;
  LifeRangeBase(LifeRangeBase &&) = delete;
  LifeRangeBase& operator=(LifeRangeBase &&) = delete;
  ~LifeRangeBase() = default;

  /// Returns the command-line argument attached to this pass.
  static constexpr ::llvm::StringLiteral getArgumentName() {
    return ::llvm::StringLiteral("life-range");
  }
  ::llvm::StringRef getArgument() const override { return "life-range"; }

  ::llvm::StringRef getDescription() const override { return "Life Range Pass to show life cycles of variables"; }

  /// Returns the derived pass name.
  static constexpr ::llvm::StringLiteral getPassName() {
    return ::llvm::StringLiteral("LifeRange");
  }
  ::llvm::StringRef getName() const override { return "LifeRange"; }

  /// Support isa/dyn_cast functionality for the derived pass class.
  static bool classof(const ::mlir::Pass *pass) {
    return pass->getTypeID() == ::mlir::TypeID::get<DerivedT>();
  }

  /// A clone method to create a copy of this pass.
  std::unique_ptr<::mlir::Pass> clonePass() const override {
    return std::make_unique<DerivedT>(*static_cast<const DerivedT *>(this));
  }

  /// Register the dialects that must be loaded in the context before this pass.
  void getDependentDialects(::mlir::DialectRegistry &registry) const override {
    registry.insert<memref::MemRefDialect>();
  }

  /// Explicitly declare the TypeID for this class. We declare an explicit private
  /// instantiation because Pass classes should only be visible by the current
  /// library.
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(LifeRangeBase<DerivedT>)

protected:
};
#undef GEN_PASS_CLASSES
#endif // GEN_PASS_CLASSES
